CREATE DATABASE MYSHOP;
 

CREATE TABLE CUSTOMER (
CSID int NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
SHOPNAME VARCHAR(100) NOT NULL,
ADDRESS1 VARCHAR(200) NOT NULL,
ADDRESS2 VARCHAR(200) ,
CITY VARCHAR(50) NOT NULL,
STATE VARCHAR(50) NOT NULL,
PINCODE int(6),
MOBILE1 VARCHAR(12) NOT NULL,
MOBILE2 VARCHAR(12) ,
LANDLINE VARCHAR(10),
GSTNO VARCHAR(20) NOT NULL,
REFERENCE VARCHAR(150),
CREATED_DATE VARCHAR(15), 
PRIMARY KEY (CSID)
);

 
CREATE TABLE INVOICE (
INVID int NOT NULL AUTO_INCREMENT,
INVJSON VARCHAR(5000) NOT NULL,
TOTALAMOUNT int(8) NOT NULL,
GSTNO VARCHAR(20) NOT NULL,
TRANSPORTAMOUNT int(5) NOT NULL,
TRANSPORTID VARCHAR(20) NOT NULL,
DATE date,
CSID int NOT NULL,
PRIMARY KEY (INVID),
FOREIGN KEY (CSID) REFERENCES CUSTOMER(CSID)
);


CREATE TABLE USERS (
  USERID int NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  CREATEDATE date,
  ROLE VARCHAR(15) NOT NULL,
  PRIMARY KEY (USERID)
  );
  
  INSERT INTO USERS VALUES (1,"admin","admin",curdate(),"ADMIN");